#!/usr/bin/env python3
import argparse
import json
import os
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

STDLIB_MODULES = {"std", "std.compat"}


def scan_source(scan_deps: str, cxx: str, cxxflags: list[str], source: str) -> dict:
    cmd = [
        scan_deps,
        "-format=p1689",
        "--",
        cxx,
        *cxxflags,
        "-x",
        "c++-module",
        source,
        "-c",
        "-o",
        "/dev/null",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"error: scan failed for {source}", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)

    return json.loads(result.stdout)


def build_graph(scan_results: list[tuple[str, dict]]) -> tuple[
    dict[str, str],
    dict[str, list[str]],
]:
    providers = {}
    requires = {}

    for source, p1689 in scan_results:
        for rule in p1689.get("rules", []):
            provided = [p["logical-name"] for p in rule.get("provides", [])]
            required = [r["logical-name"] for r in rule.get("requires", [])]
            for mod in provided:
                if mod in providers:
                    print(
                        f"error: module '{mod}' provided by both "
                        f"'{providers[mod]}' and '{source}'",
                        file=sys.stderr,
                    )
                    sys.exit(1)

                providers[mod] = source
                requires[mod] = required

    return providers, requires


def toposort(providers: dict[str, str], requires: dict[str, list[str]]) -> list[str]:
    UNMARKED, TEMPORARY, PERMANENT = 0, 1, 2
    marks = defaultdict(int)
    order = []

    def visit(node: str, path: list[str]):
        if marks[node] == PERMANENT:
            return

        if marks[node] == TEMPORARY:
            cycle = " -> ".join(path[path.index(node) :] + [node])
            print(f"error: module dependency cycle: {cycle}", file=sys.stderr)
            sys.exit(1)

        marks[node] = TEMPORARY
        for dep in requires.get(node, []):
            if dep not in providers:
                continue

            visit(dep, path + [node])
        marks[node] = PERMANENT
        order.append(node)

    for mod in providers:
        if marks[mod] == UNMARKED:
            visit(mod, [])

    return order


def module_to_pcm(mod: str, pcm_dir: str) -> str:
    return os.path.join(pcm_dir, f"{mod}.pcm")


def module_to_obj(mod: str, obj_dir: str) -> str:
    return os.path.join(obj_dir, f"{mod}.pcm.o")


def emit_makefile(
    order: list[str],
    providers: dict[str, str],
    requires: dict[str, list[str]],
    toplevel: str,
    pcm_dir: str,
    obj_dir: str,
    output: str,
):
    os.makedirs(os.path.dirname(output), exist_ok=True)

    mod_to_pcm = {}

    for stdlib_mod in STDLIB_MODULES:
        mod_to_pcm[stdlib_mod] = os.path.join(pcm_dir, f"{stdlib_mod}.pcm")

    for mod in order:
        mod_to_pcm[mod] = module_to_pcm(mod, pcm_dir)

    with open(output, "w") as f:
        f.write("# Auto-generated by scan_modules.py - do not edit\n")
        f.write(f"# Modules discovered: {len(order)}\n\n")

        all_pcms = [mod_to_pcm[m] for m in order]
        all_pcm_objs = []

        f.write(
            f"MODULE_PCM_FILES := $(STD_PCM) $(STD_COMPAT_PCM) "
            f"{' '.join(all_pcms)}\n\n"
        )

        for mod in order:
            src = providers[mod]
            pcm = mod_to_pcm[mod]
            obj = module_to_obj(mod, obj_dir)
            all_pcm_objs.append(obj)
            deps = requires.get(mod, [])

            mod_flags = []
            pcm_prereqs = []
            for dep in deps:
                if dep in mod_to_pcm:
                    mod_flags.append(f"-fmodule-file={dep}={mod_to_pcm[dep]}")
                    pcm_prereqs.append(mod_to_pcm[dep])

            flags_str = " ".join(mod_flags)

            f.write(f"# module: {mod}\n")
            all_prereqs = [src] + pcm_prereqs
            f.write(f"{pcm}: {' '.join(all_prereqs)}\n")
            f.write(f"\t$(call precompile-module,{src},{pcm},{flags_str})\n\n")

            f.write(f"{obj}: {pcm}\n")
            f.write(f"\t$(call compile-pcm,{pcm},{obj})\n\n")

        f.write(f"MODULE_OBJS := $(STD_OBJ) {' '.join(all_pcm_objs)}\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cxx", required=True)
    parser.add_argument("--cxxflags", required=True)
    parser.add_argument("--scan-deps", required=True)
    parser.add_argument("--pcm-dir", required=True)
    parser.add_argument("--obj-dir", required=True)
    parser.add_argument("--dep-dir", required=True)
    parser.add_argument("--toplevel", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("sources", nargs="+")

    args = parser.parse_args()
    cxxflags = args.cxxflags.split()

    scan_results = []
    for src in args.sources:
        p1689 = scan_source(args.scan_deps, args.cxx, cxxflags, src)
        scan_results.append((src, p1689))

    providers, requires = build_graph(scan_results)
    order = toposort(providers, requires)

    emit_makefile(
        order,
        providers,
        requires,
        args.toplevel,
        args.pcm_dir,
        args.obj_dir,
        args.output,
    )

    print(f"  SCAN     {len(order)} modules -> {args.output}")


if __name__ == "__main__":
    main()
